name: first-github-action
on: [push]
jobs:
  write-to-console:
    name: Write to console
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1

      - name: Command Group
        run: |
          echo 'Hello World!'
          echo 'Hello again!'
