name: first-github-action
on: [push]
jobs:
  write-to-console:
    name: Write to console
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Using Name + uses
      - name: Setup Node
        uses: actions/setup-node@v1

      # Using Name + Run
      - name: Say Hello
        run: echo 'Hello World!'
      - run: echo "Another section 😉"
